### ISSUE TITLE
SAIGA normal assessment on COLMAP-ADOP converted dataset - own scene training. 

### ISSUE THREAD

**Issue by gaetan-landreau** [lfranke/VET#4]
Hi ! 
Thanks for the amazing work you've made through VET ! Truly awesome. 🤗
I managed to build up your project entirely, convert my own COLMAP scene to the ADOP format, but when I try to launch a training with the current : 
```bash
./build/bin/train --config configs/config.ini
```
I get some error at step 1 / epoch 1: 

```bash
Assertion 'n.allFinite()' failed!
  File: /home/gaetan/VET/src/lib/rendering/NeuralPointCloudCuda.cpp:33
  Function: NeuralPointCloudCudaImpl::NeuralPointCloudCudaImpl(const Saiga::UnifiedMesh&, bool, float, Saiga::AABB)
Aborted (core dumped)
````
I'm not 100% sure about the issue but it seems related to some normal vector assessment using SAIGA (making sure there are no NaN values ?) 
I commented the line, rebuild the project, training seems to be stable for now...

**Comment by lfranke** [comment]
Hi, 
that should be fine! Point normals are not used at the moment in the VET code
